import { auth } from "@/auth";
import AuthFooter from "@/components/auth/Footer";
import { redirect } from "next/navigation";
import "../globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function AuthLayout({ children }) {
  const session = await auth();

  if (session?.user) {
    redirect("/");
  }

  return (
    <div className="bg-white text-amazon-text flex flex-col min-h-screen items-center pt-8">
      {children}
      <AuthFooter />
    </div>
  );
}
